import type { Metadata } from "next";
import "./globals.css";

import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <NextUIProvider>
                    <NextThemesProvider attribute="class" defaultTheme="dark">
                        <section className="min-h-screen flex flex-col">
                            <Header />
                            {children}
                        </section>
                    </NextThemesProvider>
                </NextUIProvider>
            </body>
        </html>
    );
}
